
# Site settings
title:                    Tien Phan
name:                     Tien Phan
subtitle:                 Small Steps to a Thousand-mile Journey
codetitle:                Coding
codesubtitle:             It's harder to read code than to write it. - Joel Spolsky
mltitle:                  Machine Learning
mlsubtitle:               Predicting the future isn't magic, it's AI. - Dave Water 
email:                    minhtien@phys.ksu.edu
description: >
  A personal website about technical things I find useful. Also, random ramblings and rants.
baseurl:                  ""
url:                      "https://tienmphan.github.io"
twitter_username:         PhanBiophys
github_username:          TienMPhan
disqus_baseurl:           "https://TienMPhan.github.io/"
disqus_shortname:         https-TienMPhan-github-io
permalink:                :title
cover:                    "/assets/header_image.jpg"
headimg:                  "/assets/cover1.jpg"
mlimg:                    "/assets/mlcover.jpg"
logo:                     "/assets/tp-logo.png"
avatar:                   "/assets/cat.gif"
ga_tracking_id:           "NAY"

# Build settings
markdown:                 kramdown
paginate:                 5
paginate_path:            "/page:num/"
inter_post_navigation:    true

highlightjs_theme:        "atom-one-dark"

defaults:
  -
    scope:
      path:               ""
    values:
      author:             "Tien Phan"


kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3

# External gems
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag

exclude:
  - "/vendor/"

# Collections
collections:
  research:
    output: true
    permalink: /research/:path/
  coding:
    output: true
    permalink: /coding/:path/
  ml:
    output: true
    permalink: /coding/:path/

#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts

social:
  - name:                 Twitter
    icon:                 twitter
    username:             PhanBiophys
    url:                  https://twitter.com/PhanBiophys
    desc:                 Follow me on Twitter
    share:                false

  - name: Quora
    icon: quora
    username:
    url:
    desc: Follow me on Quora
    share: flase

  - name: GitHub
    icon: github
    username: tien
    url: https://github.com/tienmphan
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username:
    url:
    desc: Connect with me on LinkedIn
    share: false

  - name: Google+
    icon: google-plus
    username:
    url:
    desc: Add me to your Circles
    share: false

  - name: YouTube
    icon: youtube
    username:
    url:
    desc: Subscribe on YouTube
    share: false

  - name: Instagram
    icon: instagram
    username:
    url:
    desc: Follow me on Instagram
    share: false

  - name: Pinterest
    icon: pinterest
    username:
    url:
    desc: Follow me on Pinterest
    share: false

  - name: SoundCloud
    icon: soundcloud
    username:
    url:
    desc: Follow me on SoundCloud
    share: false

  - name: Tumblr
    icon: tumblr
    username:
    url:
    desc: Follow me on Tumblr
    share: false

  - name: Steam
    icon: steam
    username:
    url:
    desc: Friend me on Steam
    share: false

  - name: Dribbble
    icon: dribbble
    username:
    url:
    desc: Follow me on Dribble
    share: false

  - name: Vimeo
    icon: vimeo-square
    username:
    url:
    desc: Follow me on Vimeo
    share: false

  - name: Vine
    icon: vine
    username:
    url:
    desc: Follow me on Vine
    share: false

  - name: Reddit
    icon: reddit
    username:
    url:
    desc: Share to Reddit
    share: false

  - name: "Hacker News"
    icon: hacker-news
    username:
    url:
    desc: Share to Hacker News
    share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/tp-logo.png"
    fb_image_width: 512         #612
    fb_image_height: 512        #605
    fb_image_type: "image/png"

    twitter_image: "/assets/tp-logo.png"

    os_repo: "https://github.com/tienmphan/tienmphan.github.io"
    os_rcs_type: "git"
    os_src: "git@github.com:tienmphan.github.io.git"
